defaults:
  - default
  - _self_

# Override from `default` config
id: Breakout-v1
action_repeat: 1
capture_video: False
screen_size: 8

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.minatar.MinAtarWrapper
  id: ${env.id}
  render_mode: rgb_array
  use_minimal_action_set: False,
