defaults:
  - default
  - _self_

# Override from `default` config
action_repeat: 4
id: MsPacmanNoFrameskip-v4
max_episode_steps: 27000

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.custom_atari_preprocessing.CustomAtariPreprocessing 
  env:
    _target_: sheeprl.envs.ocatari.OCAtariWrapper
    obs_mode: ori
    id: ${env.id}
    render_mode: rgb_array
  noop_max: 30
  terminal_on_life_loss: False
  frame_skip: ${env.action_repeat}
  screen_size: ${env.screen_size}
  grayscale_obs: ${env.grayscale}
  scale_obs: False
  grayscale_newaxis: True