defaults:
  - default
  - _self_

# Override from `default` config
action_repeat: 4
id: MsPacmanNoFrameskip-v4
max_episode_steps: 27000

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.ocatariw.OCAtariWrapper
  id: ${env.id} 
  render_mode: rgb_array
  obs_mode: dqn