# @package _global_

defaults:
  - dreamer_v3
  - override /env: ocatari
  - _self_

# Experiment
seed: 5

# Fabric
fabric:
  accelerator: gpu
  devices: [0]

# Environment
env:
  num_envs: 1
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4

# Checkpoint
checkpoint:
  every: 2000

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  cnn_keys:
    encoder:
      - rgb
  mlp_keys:
    encoder: 
      - objects_position
  learning_starts: 1024
  total_steps: 100000
  train_every: 8
  dense_units: 512
  mlp_layers: 2
  world_model:
    encoder:
      cnn_channels_multiplier: 32
    recurrent_model:
      recurrent_state_size: 512
    transition_model:
      hidden_size: 512
    representation_model:
      hidden_size: 512
